spring.datasource.username=postgres
spring.datasource.password=example
spring.datasource.url=jdbc:postgresql://postgres:5432/url_db

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}

